[package]
name = "challenge-0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
crc32fast = "1.3.2"
indicatif = { version = "*", features = ["rayon"] }
rayon = "1.8.0"
